package com.busantrip.service;

import com.busantrip.controller.RouteController.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;
import java.util.*;

@Service
public class RouteOptimizationService {
    private final WebClient client; private final ObjectMapper mapper; private final String keyId,keySecret;
    public RouteOptimizationService(WebClient.Builder b,ObjectMapper mapper,@Value("${external-api.naver-directions.base-url:https://maps.apigw.ntruss.com}") String base,@Value("${external-api.naver-directions.key-id:}") String keyId,@Value("${external-api.naver-directions.key-secret:}") String keySecret){this.client=b.baseUrl(base.trim()).build();this.mapper=mapper;this.keyId=keyId.trim();this.keySecret=keySecret.trim();}
    public Mono<RouteResponse> optimize(RouteRequest request){if(request==null||request.start()==null||request.places()==null||request.places().isEmpty())return Mono.error(new IllegalArgumentException("출발지와 장소가 필요합니다."));List<Place> ordered=twoOpt(nearest(request.start(),request.places()),request.start());if(keyId.isBlank()||keySecret.isBlank())return Mono.just(fallback(request.start(),ordered,request.option()));return callAll(request.start(),ordered,request.option()).onErrorReturn(fallback(request.start(),ordered,request.option()));}

    private Mono<RouteResponse> callAll(Coordinate start,List<Place> ordered,String option){
        List<Mono<RouteResponse>> calls=new ArrayList<>(); Coordinate segmentStart=start; int index=0;
        while(index<ordered.size()){int end=Math.min(ordered.size(),index+16);List<Place> chunk=new ArrayList<>(ordered.subList(index,end));calls.add(call(segmentStart,chunk,option));Place last=chunk.get(chunk.size()-1);segmentStart=new Coordinate(last.latitude(),last.longitude());index=end;}
        return Mono.zip(calls,values->{List<Coordinate> path=new ArrayList<>();List<Guide> guides=new ArrayList<>();long meters=0,duration=0;int offset=0;for(Object value:values){RouteResponse r=(RouteResponse)value;List<Coordinate> segment=new ArrayList<>(r.path());if(!path.isEmpty()&&!segment.isEmpty())segment.remove(0);path.addAll(segment);for(Guide g:r.guides())guides.add(new Guide(g.instruction(),g.distanceMeters(),g.durationMillis(),g.pointIndex()+offset));offset=Math.max(0,path.size()-1);meters+=r.totalDistanceMeters();duration+=r.totalDurationMillis();}return new RouteResponse(ordered,path,guides,meters,duration,false,option==null?"trafast":option);});
    }
    private Mono<RouteResponse> call(Coordinate start,List<Place> ordered,String option){Place goal=ordered.get(ordered.size()-1);String waypoints=ordered.size()<=1?null:ordered.subList(0,ordered.size()-1).stream().map(p->p.longitude()+","+p.latitude()).reduce((a,b)->a+"|"+b).orElse(null);return client.get().uri(u->{var x=u.path("/map-direction-15/v1/driving").queryParam("start",start.longitude()+","+start.latitude()).queryParam("goal",goal.longitude()+","+goal.latitude()).queryParam("option",option==null?"trafast":option);if(waypoints!=null)x.queryParam("waypoints",waypoints);return x.build();}).header("x-ncp-apigw-api-key-id",keyId).header("x-ncp-apigw-api-key",keySecret).retrieve().bodyToMono(String.class).map(json->parse(json,ordered,option));}
    private RouteResponse parse(String json,List<Place> ordered,String option){try{JsonNode root=mapper.readTree(json),route=root.path("route"),arr=route.elements().hasNext()?route.elements().next():null;if(arr==null||!arr.isArray()||arr.isEmpty())throw new IllegalStateException();JsonNode first=arr.get(0),summary=first.path("summary");List<Coordinate> path=new ArrayList<>();first.path("path").forEach(p->path.add(new Coordinate(p.get(1).asDouble(),p.get(0).asDouble())));List<Guide> guides=new ArrayList<>();first.path("guide").forEach(g->guides.add(new Guide(g.path("instructions").asText("경로를 따라 이동하세요"),g.path("distance").asLong(),g.path("duration").asLong(),g.path("pointIndex").asInt())));return new RouteResponse(ordered,path,guides,summary.path("distance").asLong(),summary.path("duration").asLong(),false,option==null?"trafast":option);}catch(Exception e){throw new IllegalStateException("Directions 응답 파싱 실패",e);}}
    private List<Place> nearest(Coordinate start,List<Place> input){List<Place> remain=new ArrayList<>(input),out=new ArrayList<>();double lat=start.latitude(),lng=start.longitude();while(!remain.isEmpty()){Place best=null;double d=Double.MAX_VALUE;for(Place p:remain){double x=h(lat,lng,p.latitude(),p.longitude());if(x<d){d=x;best=p;}}out.add(best);remain.remove(best);lat=best.latitude();lng=best.longitude();}return out;}
    private List<Place> twoOpt(List<Place> original,Coordinate start){List<Place> best=new ArrayList<>(original);double bd=total(start,best);boolean improved=true;int guard=0;while(improved&&guard++<25){improved=false;for(int i=0;i<best.size()-1;i++)for(int j=i+1;j<best.size();j++){List<Place> c=new ArrayList<>(best);Collections.reverse(c.subList(i,j+1));double cd=total(start,c);if(cd+.001<bd){best=c;bd=cd;improved=true;}}}return best;}
    private double total(Coordinate s,List<Place> p){double r=0,lat=s.latitude(),lng=s.longitude();for(Place x:p){r+=h(lat,lng,x.latitude(),x.longitude());lat=x.latitude();lng=x.longitude();}return r;}
    private double h(double a,double b,double c,double d){double R=6371.0088,da=Math.toRadians(c-a),db=Math.toRadians(d-b),q=Math.sin(da/2)*Math.sin(da/2)+Math.cos(Math.toRadians(a))*Math.cos(Math.toRadians(c))*Math.sin(db/2)*Math.sin(db/2);return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
    private RouteResponse fallback(Coordinate start,List<Place> ordered,String option){List<Coordinate> path=new ArrayList<>();path.add(start);long meters=0;double lat=start.latitude(),lng=start.longitude();for(Place p:ordered){path.add(new Coordinate(p.latitude(),p.longitude()));meters+=Math.round(h(lat,lng,p.latitude(),p.longitude())*1000);lat=p.latitude();lng=p.longitude();}long duration=Math.round(meters/8.5*1000);return new RouteResponse(ordered,path,List.of(new Guide("Directions 키가 없어 직선 기반 미리보기 경로를 표시합니다.",meters,duration,0)),meters,duration,true,option==null?"trafast":option);}
}
